#!/usr/bin/env bash
# Prints out subdomain, record type and destination

if [ $# -eq 2 ]; then
    echo -n "The subdomain $2"
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print " is a " $4 " record and points to " $5}'
else
    arr=( "www" "lb-01" "web-01" "web-02" )
    for i in "${arr[@]}" ; do
        echo -n "The subdomain $i"
        dig $i.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print " is a " $4 " record and points to " $5}'
    done
fi
