#!/usr/bin/env bash
# Adds a custom HTTP Header
apt-get -y update
apt-get -y install nginx
new_string="\tlocation \/\n\t\tadd_header X-Served-By $HOSTNAME;\n"
sed -i "s/^\tlocation \//$new_string/" /etc/nginx/sites-available/default
service nginx restart
