#!/usr/bin/env bash
# runs and listens on port 80
new_string="include /etc/nginx/sites-available/*;"
sed -i -e "s/include /etc/nginx/sites-enabled/*;/$new_string/" /etc/nginx/nginx.conf
sudo service nginx restart
