#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
if [ -e $"closchool" ]
then
	echo "closchool file exists"
	if [ -s "closchool" ]
	then
		echo "closchool file is not empty"
	else
		echo "closchool file is empty"
	fi
	if [ -f "closchool" ]
	then
		echo "closchool is a regular file"
	fi
else
	echo "closchool file does not exist"
fi
