#!/usr/bin/env bash
# Configures server to redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
new_string="server_name localhost;\n\nlocation \/redirect_me {\nrewrite ^\/(.*)$ https:\/\/www.google.com permanent;\n}"
sed -i "s/server_name localhost;/$new_string/" /etc/nginx/sites-available/default
sudo service nginx start
