#!/usr/bin/env bash
# Configures container to run as nginx user
pkill apache2
sed -i 's/80/8080/' /etc/nginx/sites-enabled/*
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo service nginx restart
