#!/usr/bin/env bash
# Configures container to run as nginx user
pkill -f apache2
sed -i 's/80/8080/' /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
