#!/usr/bin/env bash
# Configures container to run as nginx user
sed -i '1s/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/*
chown nginx /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sudo service nginx restart
